name: Test

on: [push, pull_request]

env:
    DATABASE_URL: ${{secrets.DATABASE_URL}}
    NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
    NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
    DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
    DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}
    GOOGLE_ID: ${{secrets.GOOGLE_ID}}
    GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}
    GITHUB_ID: ${{secrets.GH_ID}}
    GITHUB_SECRET: ${{secrets.GH_SECRET}}

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'
            - run: pnpm install --no-frozen-lockfile
            - run: pnpm run lint
    production-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'
            - run: pnpm install --no-frozen-lockfile
            - run: pnpm run build
